backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'assets/images'

collections:
  # General Website Settings
  - name: 'website-settings'
    label: 'Website Settings'
    files:
      # Box settings
      - label: "Box Settings"
        name: boxes
        file: "_data/boxes.yml"
        editor:
          preview: false
        fields:
          - label: Box Items
            name: items
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Link, name: link, hint: Provide the URL for the box to link to, widget: string}
              - {label: Link Text, name: link_text, hint: Provide the text for the URL link, widget: string}
              - {label: Icon Class, name: icon_class, hint: Select the icon class, widget: 'select', options: ["fa fa-star-half-empty", "fa fa-image", "fa fa-dot-circle-o"]}
              - {label: Text, name: text, hint: Provide some descriptive text for the box item, widget: text}
            
